version: '3.8'

services:
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        buildNo: ${MYSQL_VERSION}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --interactive-timeout=120 --wait-timeout=120 --explicit_defaults_for_timestamp
    container_name: ${APP_NAME}-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      #      This will not work Becuase the issue see : https://stackoverflow.com/questions/66831863/mysql-docker-container-keeps-restarting
      #      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #      MYSQL_USER: ${MYSQL_USER}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - database:/var/lib/mysql:delegated
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - "db"
    container_name: ${APP_NAME}-fpm
    working_dir: /usr/local/apache2/htdocs
    volumes:
      - .:/usr/local/apache2/htdocs:cached
      - ./node_modules:/usr/local/apache2/htdocs/node_modules:cached
      - ./public:/usr/local/apache2/htdocs/public:cached
      - ./vendor:/usr/local/apache2/htdocs/vendor:cached
      - ./var/cache:/usr/local/apache2/htdocs/var/cache:delegated
  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    depends_on:
      - "php"
    container_name: ${APP_NAME}-web
    domainname: ${HTTPD_DOMAIN}
    ports:
      - ${HTTPD_PORT}:80
    volumes:
      - ./public:/usr/local/apache2/htdocs/public:cached
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:cached
      - ./docker/apache/symfony.conf:/usr/local/apache2/conf/symfony.conf:cached
      - ./docker/apache/php-fpm.conf:/usr/local/apache2/conf/php-fpm.conf:cached
      - ./docker/apache/rewrite.conf:/usr/local/apache2/conf/rewrite.conf:cached
volumes:
  database:
